name: Deployment

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: megastruktur/python-vrg-servitor

jobs:
  docker_build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Check Out the repo
        uses: actions/checkout@v2
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          secrets: |
            GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}"
            GROUP_CHAT_ID=${{ secrets.GROUP_CHAT_ID }}
            BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
            SHEET_ID=${{ secrets.SHEET_ID }}
            LOCALE=${{ secrets.LOCALE }}
            SERVICE_ACCOUNT_SECRET_JSON_B64=${{ secrets.SERVICE_ACCOUNT_SECRET_JSON_B64 }}
