name: Deployment

on:
  push:
    branches:
      - 'master'
jobs:
  docker_build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Check Out the repo
#        uses: actions/checkout@v2
#      -
#        name: Log in to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Test Env Secrets
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          LOCALE: ${{ secrets.LOCALE }}
        run: |
          echo "$GOOGLE_API_KEY" | base64
          echo $GROUP_CHAT_ID | base64
          echo $BOT_TOKEN | base64
          echo $SHEET_ID | base64
          echo $LOCALE | base64
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          tags: megastruktur/python-vrg-servitor:latest
#          push: true
#          secrets: |
#            "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}"
#            "GROUP_CHAT_ID=${{ secrets.GROUP_CHAT_ID }}"
#            "BOT_TOKEN=${{ secrets.BOT_TOKEN }}"
#            "SHEET_ID=${{ secrets.SHEET_ID }}"
#            "LOCALE=${{ secrets.LOCALE }}"
